[package]
name = "solarscuffle-bot/connectutil"
version = "2.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

description = "A lot of helpful utilities for reducing the amount of boilerplate connection code in codebases, making certain tasks like reactive state management a breeze."

[dependencies]
